apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  serviceName: "frontend"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: frontend/frontendserver:latest
        name: frontend
        resources:
          limits:
            memory: "2Gi"
          requests:
            memory: "1Gi"
        ports:
        - name: http
          containerPort: 8096
        - name: https
          containerPort: 8920
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 600
          periodSeconds: 10
